/**
 * Mock Product Data
 * Temporary mock data for development
 */

import type { Product, Category } from './types';

export const mockCategories: Category[] = [
  { id: '1', name: 'إلكترونيات', icon: '📱' },
  { id: '2', name: 'أزياء', icon: '👔' },
  { id: '3', name: 'أغذية', icon: '🍔' },
  { id: '4', name: 'كتب', icon: '📚' },
  { id: '5', name: 'رياضة', icon: '⚽' },
  { id: '6', name: 'أثاث', icon: '🛋️' },
];

export const mockProducts: Product[] = [
  {
    _id: '1',
    name: 'هاتف Samsung Galaxy S23',
    description: 'هاتف ذكي بمواصفات عالية وكاميرا احترافية',
    category: '1',
    categoryAr: 'إلكترونيات',
    price: 2500000,
    compareAtPrice: 2800000,
    sku: 'PHONE-S23-001',
    barcode: '1234567890123',
    images: ['https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400'],
    status: 'active',
    inventory: {
      quantity: 15,
      lowStockThreshold: 5,
      trackInventory: true,
    },
    sales: 45,
    views: 1250,
    tags: ['جديد', 'عرض خاص'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '2',
    name: 'لابتوب Dell XPS 15',
    description: 'لابتوب قوي للمحترفين مع شاشة 4K',
    category: '1',
    categoryAr: 'إلكترونيات',
    price: 4200000,
    sku: 'LAPTOP-XPS15-001',
    images: ['https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400'],
    status: 'active',
    inventory: {
      quantity: 8,
      lowStockThreshold: 3,
      trackInventory: true,
    },
    sales: 32,
    views: 890,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '3',
    name: 'سماعات Sony WH-1000XM5',
    description: 'سماعات لاسلكية مع إلغاء ضوضاء نشط',
    category: '1',
    categoryAr: 'إلكترونيات',
    price: 850000,
    compareAtPrice: 950000,
    sku: 'HEADPHONE-SONY-001',
    images: ['https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400'],
    status: 'active',
    inventory: {
      quantity: 22,
      lowStockThreshold: 10,
      trackInventory: true,
    },
    sales: 28,
    views: 650,
    tags: ['الأكثر مبيعاً'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '4',
    name: 'ساعة Apple Watch Series 9',
    description: 'ساعة ذكية مع مستشعرات صحية متقدمة',
    category: '1',
    categoryAr: 'إلكترونيات',
    price: 1200000,
    sku: 'WATCH-APPLE-001',
    images: ['https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=400'],
    status: 'active',
    inventory: {
      quantity: 3,
      lowStockThreshold: 5,
      trackInventory: true,
    },
    sales: 18,
    views: 420,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '5',
    name: 'كاميرا Canon EOS R6',
    description: 'كاميرا احترافية للتصوير الفوتوغرافي',
    category: '1',
    categoryAr: 'إلكترونيات',
    price: 5500000,
    sku: 'CAMERA-CANON-001',
    images: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400'],
    status: 'draft',
    inventory: {
      quantity: 0,
      lowStockThreshold: 2,
      trackInventory: true,
    },
    sales: 0,
    views: 120,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '6',
    name: 'تيشيرت قطن 100%',
    description: 'تيشيرت قطني مريح بألوان متعددة',
    category: '2',
    categoryAr: 'أزياء',
    price: 150000,
    compareAtPrice: 200000,
    sku: 'TSHIRT-001',
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400'],
    status: 'active',
    inventory: {
      quantity: 50,
      lowStockThreshold: 20,
      trackInventory: true,
    },
    sales: 120,
    views: 2100,
    variants: [
      { name: 'اللون', options: ['أبيض', 'أسود', 'أزرق'] },
      { name: 'المقاس', options: ['S', 'M', 'L', 'XL'] },
    ],
    tags: ['قطن', 'صيفي'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

